ToDoList.Site/Controllers/HomeController.cs
using System.Web.Mvc;

namespace ToDoList.Site.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }
    }
}

ToDoList.Site/Controllers/PrioritiesController.cs
using System.Linq;
using System.Web.Mvc;
using ToDoList.Core.Models;
using ToDoList.Core.Services;

namespace ToDoList.Site.Controllers
{
    public class PrioritiesController : BasicController
    {
        protected readonly IPrioritiesService PrioritiesService;

        public PrioritiesController(IPrioritiesService prioritiesService)
        {
            PrioritiesService = prioritiesService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            var priorities = PrioritiesService.List(CurrentUserId);
            return Json(priorities.Select(p => new { id = p.Id, name = p.Name }), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ActualList()
        {
            var priorities = PrioritiesService.ActualPriorities(CurrentUserId);
            return Json(priorities.Select(p => new { id = p.Id, name = p.Name }), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Add(string name)
        {
            var priority = new Priority { Name = name, UserId = CurrentUserId };
            var result = PrioritiesService.AddOrUpdate(priority);
            return Json(result.ToJson(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Update(int id, string name)
        {
            var result = PrioritiesService.ChangeName(id, CurrentUserId, name);
            return Json(result.ToJson(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var result = PrioritiesService.Delete(id, CurrentUserId);
            return Json(result.ToJson(), JsonRequestBehavior.AllowGet);
        }
    }
}

ToDoList.Site/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="add-button" id="add-note"></div>
<div class="notes-filter">
    <select class="form-control" id="priority-filter"></select>
    <input class="form-control" id="search" placeholder="Search"/>
    <span class="label label-primary" id="state">active</span>
    <span id="time-filter"><i class="glyphicon glyphicon-time"></i><i class="glyphicon glyphicon-menu-down" id="direction"></i></span>
</div>
<div class="" id="notes-list"></div>

<form class="modal fade" id="add-note-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">add note</h4>
            </div>
            <div class="modal-body">
                <div id="errors"></div>
                <div class="form-group">
                    <label class="control-label field-title">name</label>
                    <input type="hidden" class="form-control" id="id"/>
                    <input type="text" class="form-control" id="name" name="name"/>
                </div>
                <div class="form-group">
                    <label class="control-label field-title">priority</label>
                    <div>
                        <select class="form-control priority-select" id="priority" name="priority"></select>
                        <a class="edit-priorities" href="@Url.Action("Index", "Priorities")">edit</a>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label field-title">description</label>
                    <textarea class="form-control" id="description"></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success" id="btn-add-note">add</button>
            </div>
        </div>
    </div>
</form>

<div></div>
@section scripts {
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script type="text/javascript" src="~/Scripts/site/notes.js"></script>
}